### PR TITLE
Fix typo in Dispenser Manager error log

### PR DESCRIPTION
**Pull request by Phlosioneer**
Changed "Error white" to "Error while"

### CODE REVIEW

**Comment by MehVahdJukaar** [comment]
So actually which items is this happening to? The error I mean

**Comment by Phlosioneer** [comment]
Here's the error. I haven't determined yet whether it's this mod's fault, or alexsmobs fault, or if either mod has updates to fix it; this is also among a ton of other mods, so I haven't checked if removing other mods fixes the issue. Minecraft 1.19.2, Forge 43.2.11, alexsmobs 1.21.1, supplementaries 1.19.2-2.3.10.

```
[23:49:44] [Render thread/WARN] [supplementaries/]: Error white registering dispenser behavior for item medium_catfish_bucket: java.lang.IllegalArgumentException: value already present: entity.alexsmobs.catfish
[23:49:44] [Render thread/WARN] [supplementaries/]: Error white registering dispenser behavior for item large_catfish_bucket: java.lang.IllegalArgumentException: value already present: entity.alexsmobs.catfish
[23:49:44] [Render thread/INFO] [supplementaries/]: Finished additional setup in 86 ms
```

If I isolate the problem I'll open an issue for it.

**Comment by Phlosioneer** [comment]
`alexsmobs:small_catfish_bucket` isn't mentioned in the errors, so I suspect supplementaries is not expecting three different fish-bucket items (`small_catfish_bucket`, `medium_catfish_bucket`, `large_catfish_bucket`) to produce the same entity? But that's just a guess.

**Comment by MehVahdJukaar** [comment]
Might be

**Pull request merged**
