### PR TITLE
I have a feeling this image shouldn't be here :smile:

### PR DESCRIPTION
**Pull request by NillerMedDild**
- Delete hanging_sign_front_helix_tree - Copy (2).png

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Slightly related, this file uses an unsupported char: https://github.com/MehVahdJukaar/Supplementaries/blob/master/src/main/resources/assets/supplementaries/models/block/end_lamps/end_stone_lamp_%E0%B6%9E.json
The fix for that is not suitable for the web editor though imo 😄

**Comment by MehVahdJukaar** [comment]
Oh true, how did you find it though, pretty impressive considering how many of those textures are there.
And for the end lamp it's a bit sus that it doesn't support the ඞ character lol. I wanted to have an amogus end lamp easter egg but ended up scrapping the idea and forgot to remove that. Maybe it was for the best

**Comment by NillerMedDild** [comment]
I found it because I ran into a bug that caused my instance to crash on startup for every faulty asset path :P

**Comment by MehVahdJukaar** [comment]
So I've had another report about that. Any info on what's it about? Minecraft didn't recieve any update for 1.16 so idk what made it so it now crashed with those all of a sudden

**Comment by NillerMedDild** [comment]
It's caused by a bug in an experimental Curios update: https://www.curseforge.com/minecraft/mc-mods/curios/files/3542209
It was fixed in: https://www.curseforge.com/minecraft/mc-mods/curios/files/3543047

**Pull request merged**
