### PR TITLE
41.0.100 port for Forge 1.19

### PR DESCRIPTION
**Pull request by gohkenytp**
This is for the original owner which updates the mod for 41.0.100

### CODE REVIEW

**Comment by Speiger** [comment]
@gohkenytp that doesn't fix anything...
You actually need to fix the crash that causes it.

**Comment by Speiger** [comment]
Yeah just looked at the code and Supplementaries has like 2k Errors to fix...

**Comment by gohkenytp** [comment]
I know, right. Hope the original owner fixes it in time.

**Comment by Speiger** [comment]
Eh he needs to fix already 109 if he updates to 100 (i ported a mod to 105 and it broke at 109)

**Comment by MehVahdJukaar** [comment]
yeah changing a single line of text wont do any good. I've already updated this stuff on my multi loader repo. I'm waiting to release for when I'll have a non buggy version. fabric and forge development are now somewhat tied together now so this will come when fabric version will be somewhat stable

**Pull request closed without merging**
